"""
torbunny logo: raster PNG → ASCII for the CLI banner (monochrome or truecolor).

Place your artwork at ``assets/torbunny.png`` (replace the bundled placeholder).
Regenerate embedded cache after editing the image::

    python tools/png_to_ascii.py --write

Or rely on runtime conversion (requires Pillow). Color is sampled from the PNG
at startup when Pillow and the image are available.
"""
from __future__ import annotations

from pathlib import Path

from rich.color import Color
from rich.console import Console
from rich.panel import Panel
from rich.style import Style
from rich.text import Text

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    Image = None  # type: ignore[misc, assignment]

_ASSETS = Path(__file__).resolve().parent / "assets"
_DEFAULT_PNG = _ASSETS / "torbunny.png"
# Optional pre-rendered ASCII (generated by tools/png_to_ascii.py)
_CACHED_TXT = _ASSETS / "banner_logo.txt"

# Minimal fallback if Pillow or PNG is missing
_FALLBACK_LOGO = "  torbunny\n  bunny.net · via Tor"

_RAMP = (
    " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"
)


def _luma(r: int, g: int, b: int) -> float:
    return 0.299 * r + 0.587 * g + 0.114 * b


def _boost_rgb(r: int, g: int, b: int, *, min_lum: float = 28.0) -> tuple[int, int, int]:
    """
    Slightly lift only near-black pixels so '#' glyphs stay visible on dark
    terminals. Mid-tones (orange, purple, etc.) are left unchanged so hues stay
    faithful to the source PNG.
    """
    lum = _luma(r, g, b)
    if lum >= min_lum:
        return r, g, b
    # Gentle lift toward white — only for very dark cells
    a = min(0.28, (min_lum - lum) / 180.0)
    return (
        min(255, int(r + (255 - r) * a)),
        min(255, int(g + (255 - g) * a)),
        min(255, int(b + (255 - b) * a)),
    )


def _raster_logo(
    path: Path,
    *,
    width: int = 72,
    invert_auto: bool = True,
) -> list[list[tuple[str, tuple[int, int, int]]]]:
    """
    Resize logo and return a grid of (ascii_char, rgb) per cell.

    **Luminance** (optionally inverted) picks the glyph for light-background logos.
    **RGB for the terminal is always the true pixel color** — we never invert
    colors, or orange/white/purple would show as their complements.
    """
    if Image is None:
        raise RuntimeError("Pillow is required for PNG→ASCII (pip install Pillow)")

    # RGBA → composite on white so transparent areas read as white, not black
    src = Image.open(path).convert("RGBA")
    img_rgb = Image.new("RGB", src.size, (255, 255, 255))
    img_rgb.paste(src, mask=src.split()[3])

    w0, h0 = img_rgb.size
    aspect = h0 / w0
    new_w = max(16, min(width, w0))
    new_h = max(4, int(aspect * new_w * 0.52))
    img_rgb = img_rgb.resize((new_w, new_h), Image.Resampling.LANCZOS)

    # Invert **luminance only** when the logo is mostly light (ink on paper)
    if invert_auto:
        sw = min(32, new_w)
        sh = min(32, new_h)
        sample = img_rgb.resize((sw, sh))
        mean_l = sum(_luma(*sample.getpixel((x, y))[:3]) for y in range(sh) for x in range(sw)) / (sw * sh)
        invert_luma = mean_l > 127.0
    else:
        invert_luma = False

    grid: list[list[tuple[str, tuple[int, int, int]]]] = []
    for y in range(new_h):
        row: list[tuple[str, tuple[int, int, int]]] = []
        for x in range(new_w):
            r, g, b = img_rgb.getpixel((x, y))[:3]
            p = int(_luma(r, g, b))
            if invert_luma:
                p = 255 - p
            idx = min(len(_RAMP) - 1, p * (len(_RAMP) - 1) // 255)
            row.append((_RAMP[idx], (r, g, b)))
        grid.append(row)

    # Trim leading / trailing blank lines (space-only rows)
    def row_strength(row: list[tuple[str, tuple[int, int, int]]]) -> float:
        return sum(1 for ch, _ in row if ch != _RAMP[0])

    while grid and row_strength(grid[0]) == 0:
        grid.pop(0)
    while grid and row_strength(grid[-1]) == 0:
        grid.pop()

    return grid


def png_to_ascii(
    path: Path,
    *,
    width: int = 72,
    invert_auto: bool = True,
) -> str:
    """Plain-text ASCII (no color) — for ``banner_logo.txt`` cache."""
    grid = _raster_logo(path, width=width, invert_auto=invert_auto)
    return "\n".join("".join(ch for ch, _ in row) for row in grid)


def grid_to_rich_text(
    grid: list[list[tuple[str, tuple[int, int, int]]]],
    *,
    boost: bool = True,
) -> Text:
    """Turn a char+RGB grid into a Rich `Text` with truecolor segments."""
    t = Text()
    for yi, row in enumerate(grid):
        i = 0
        n = len(row)
        while i < n:
            _, rgb0 = row[i]
            r, g, b = _boost_rgb(*rgb0) if boost else rgb0
            j = i + 1
            while j < n:
                rj, gj, bj = (
                    _boost_rgb(*row[j][1]) if boost else row[j][1]
                )
                if (rj, gj, bj) != (r, g, b):
                    break
                j += 1
            segment = "".join(row[k][0] for k in range(i, j))
            # TrueColor from exact sRGB bytes (Rich Color, not markup string)
            t.append(
                segment,
                style=Style(color=Color.from_rgb(r, g, b)),
            )
            i = j
        if yi < len(grid) - 1:
            t.append("\n")
    return t


def png_to_colored_text(
    path: Path,
    *,
    width: int = 72,
    invert_auto: bool = True,
    boost: bool = True,
) -> Text:
    """PNG → Rich `Text` with per-run truecolor from the image."""
    grid = _raster_logo(path, width=width, invert_auto=invert_auto)
    return grid_to_rich_text(grid, boost=boost)


def _load_logo_ascii() -> str:
    # 1) Pre-baked file from tools/png_to_ascii.py (fast, no Pillow at import)
    if _CACHED_TXT.is_file():
        try:
            return _CACHED_TXT.read_text(encoding="utf-8").rstrip()
        except OSError:
            pass

    # 2) Runtime conversion from PNG
    if _DEFAULT_PNG.is_file() and Image is not None:
        try:
            return png_to_ascii(_DEFAULT_PNG)
        except Exception:
            pass

    return _FALLBACK_LOGO


LOGO_ASCII = _load_logo_ascii()


def print_startup_banner(console: Console) -> None:
    """Print the torbunny logo: truecolor from PNG when possible, else cyan ASCII."""
    body: Text
    if _DEFAULT_PNG.is_file() and Image is not None:
        try:
            body = png_to_colored_text(_DEFAULT_PNG)
        except Exception:
            body = Text(LOGO_ASCII, style="bold cyan")
    else:
        body = Text(LOGO_ASCII, style="bold cyan")

    console.print()
    console.print(
        Panel(
            body,
            border_style="cyan",
            padding=(0, 2),
            expand=False,
        )
    )


__all__ = [
    "LOGO_ASCII",
    "png_to_ascii",
    "png_to_colored_text",
    "grid_to_rich_text",
    "print_startup_banner",
    "_DEFAULT_PNG",
]
